include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "build/**"
    - ".dart_tool/**"
  errors:
    invalid_annotation_target: ignore
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # Error Rules
    - always_declare_return_types
    - avoid_empty_else
    - avoid_returning_null_for_void
    - avoid_slow_async_io
    - avoid_type_to_string
    - avoid_types_as_parameter_names
    - cancel_subscriptions
    - close_sinks
    - empty_catches
    - no_duplicate_case_values
    - no_logic_in_create_state
    - unawaited_futures
    - use_build_context_synchronously
    
    # Style Rules
    - always_put_required_named_parameters_first
    - avoid_unused_constructor_parameters
    - constant_identifier_names
    - directives_ordering
    - file_names
    - flutter_style_todos
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_locals
    - prefer_if_null_operators
    - prefer_null_aware_operators
    - prefer_single_quotes
    - require_trailing_commas
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - use_full_hex_values_for_flutter_colors
    - use_key_in_widget_constructors
    
    # Additional Best Practice Rules
    - avoid_print
    - avoid_dynamic_calls
    - avoid_redundant_argument_values
    - avoid_renaming_method_parameters
    - avoid_unnecessary_containers
    - avoid_void_async
    - cascade_invocations
    - deprecated_consistency
    - eol_at_end_of_file
    - leading_newlines_in_multiline_strings
    - missing_whitespace_between_adjacent_strings
    - no_leading_underscores_for_local_identifiers
    - prefer_asserts_in_initializer_lists
    - prefer_final_in_for_each
    - prefer_interpolation_to_compose_strings
    - sized_box_for_whitespace
    - sort_child_properties_last
    - unnecessary_late
    - unnecessary_null_checks
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - use_colored_box
    - use_decorated_box
    - use_enums
    - use_if_null_to_convert_nulls_to_bools
    - use_is_even_rather_than_modulo
    - use_named_constants
    - use_string_buffers
    - use_super_parameters
